#############################################################################################################################
# change the image Docker repo to your Java base image. For now the Java base image may not be built in openshift
#However the Docker repo of your java image is predictable
#The format should be docker-registry.default.svc:5000/[name_of_openshift_project]/[name_of_Java_image]:latest
FROM docker-registry.default.svc:5000/thps-dev-project/java-docker:latest
ARG TOMCAT_MAJOR_VERSION
ARG TOMCAT_MINOR_VERSION
ARG MIRROR="http://mirror.csclub.uwaterloo.ca/apache"
###########change these variables to use different version of tomcat
ENV CATALINA_HOME="/usr/local/tomcat" \
    TOMCAT_MAJOR_VERSION=${TOMCAT_MAJOR_VERSION:-8} \
    TOMCAT_MINOR_VERSION=${TOMCAT_MINOR_VERSION:-8.5.29}
###############################################################################################################################
###################Do not change following steps
ENV PATH="${PATH}:${CATALINA_HOME}/bin"
RUN mkdir -p "${CATALINA_HOME}"
WORKDIR ${CATALINA_HOME}
RUN set -x \
    && curl -L#O "${MIRROR}/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz" \
    && curl -L#O "https://www.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.sha1" \
    && sha1sum -c "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.sha1" \
    && tar -zxf "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz" \
    && mv "apache-tomcat-${TOMCAT_MINOR_VERSION}/"* . \
    && rmdir "apache-tomcat-${TOMCAT_MINOR_VERSION}" \
    && rm bin/*.bat "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz" "apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.sha1"
EXPOSE 8080
RUN chgrp -R 0 /usr
RUN chmod -R g=u /usr
CMD ["catalina.sh", "run"]
